# Generated by Django 4.1.7 on 2023-03-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolecode',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Логист', 'Логист'), ('Снабженец', 'Снабженец'), ('Оператор', 'Оператор'), ('Водитель', 'Водитель'), ('Упаковщик', 'Упаковщик'), ('Менеджер', 'Менеджер'), ('Админ', 'Админ')], default='Пользователь', max_length=200, verbose_name='Роль которая выдается после активатции кода'),
        ),
    ]
